wkshops_home/wkshops_home/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path

from contact_book.views import ShowAllContactsView, NewContactView, ContactDetailsView, AllGroupsView, \
    AddPhoneView, AddMailView


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^main/$', ShowAllContactsView.as_view(), name="index"),
    url(r'^new/$', NewContactView.as_view(), name='new-contact'),
    url(r'^contact/(?P<contact_id>(\d+))/$', ContactDetailsView.as_view(), name='contact-details'),
    url(r'^contact/(?P<contact_id>(\d+))/add_phone/$', AddPhoneView.as_view(), name='add-phone'),
    url(r'^contact/(?P<contact_id>(\d+))/add_mail/$', AddMailView.as_view(), name='add-mail'),
    url(r'^group/show-all/$', AllGroupsView.as_view(), name='all-groups')
]

wkshops_home/contact_book/models.py
from django.db import models

# Create your models here.

CONTACT_TYPES = (
    (1, "Personal"),
    (2, "Work")
)


class Address(models.Model):
    city = models.CharField(max_length=40)
    street = models.IntegerField(max_length=10)
    house_number = models.IntegerField(max_length=10)
    app_number = models.IntegerField(max_length=10)


class Person(models.Model):
    first_name = models.CharField(max_length = 64)
    last_name = models.CharField(max_length=62)
    description = models.TextField(max_length=200)
    address = models.ForeignKey(Address, on_delete=None, null=True)

    @property
    def name(self):
        return "{} {}" .format(self.first_name, self.last_name)

    def __str__(self):
        return self.name



class Mail(models.Model):
    mail_address = models.EmailField(max_length=100)
    type = models.IntegerField(choices=CONTACT_TYPES)
    contact_person = models.ForeignKey(Person, on_delete=None)


class Phone(models.Model):
    number = models.IntegerField(max_length=20)
    type = models.IntegerField(choices= CONTACT_TYPES)
    contact_person = models.ForeignKey(Person, on_delete=None)



class ContactGroup(models.Model):
    name = models.CharField(max_length=64)
    persons = models.ManyToManyField(Person)

wkshops_home/contact_book/forms.py
from django import forms

from .models import CONTACT_TYPES



class AddPhoneForm(forms.Form):
    number = forms.IntegerField()
    type = forms.ChoiceField(choices=CONTACT_TYPES)
    contact_person = forms.IntegerField(widget=forms.HiddenInput)


class AddMailForm(forms.Form):
    address = forms.EmailField()
    type = forms.ChoiceField(choices=CONTACT_TYPES)
    contact_person = forms.IntegerField(widget=forms.HiddenInput)

wkshops_home/contact_book/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import CreateView
from django.urls import reverse_lazy

from contact_book.models import Person, Phone, Mail, Address, ContactGroup
from contact_book.forms import AddPhoneForm, AddMailForm


class NewContactView(CreateView):
    model = Person
    fields = ("first_name", "last_name", "description")
    success_url = reverse_lazy('index')


class ShowAllContactsView(View):
    def get(self, request):
        contacts = Person.objects.all()
        ctx = {
            "contacts": contacts
        }
        return render(request, "all_contacts.html", ctx)


class ContactDetailsView(View):
    def get(self, request, contact_id):
        contact = Person.objects.get(id=contact_id)
        contact_phones = Phone.objects.filter(contact_person=contact.id)
        contact_mails = Mail.objects.filter(contact_person=contact.id)
        ctx={
            'contact': contact,
            'contact_phones': contact_phones,
            'contact_mails': contact_mails
        }
        return render(request, 'contact_details.html', ctx)


class AllGroupsView(View):
    def get(self, request):
        groups = ContactGroup.objects.all()
        ctx = {
            'groups': groups
        }
        return render(request, "all_groups.html", ctx)


class AddPhoneView(View):
    def get(self, request, contact_id):
        form = AddPhoneForm(initial={
                "contact_person": contact_id
            })
        ctx ={
            "form": form
        }
        return render(request, 'add_phone_form.html', ctx)
    def post(self, request, contact_id):
        form = AddPhoneForm(request.POST)
        if form.is_valid():
            number = form.cleaned_data["number"]
            type = form.cleaned_data["type"]
            phone = Phone.objects.create(number=number, type=type, contact_person = Person.objects.get(id=contact_id))
            return redirect("contact/{}" .format(contact_id))


class AddMailView(View):
    def get(self, request, contact_id):
        form = AddMailForm(initial={
                "contact_person": contact_id
            })
        ctx ={
            "form": form
        }
        return render(request, 'add_mail_form.html', ctx)
    def post(self, request, contact_id):
        form = AddMailForm(request.POST)
        if form.is_valid():
            address = form.cleaned_data["address"]
            type = form.cleaned_data["type"]
            mail = Mail.objects.create(mail_address=address, type=type, contact_person = Person.objects.get(id=contact_id))
            return redirect("/contact/{}" .format(contact_id))

        ctx={
            "form": form
        }
        return render(request, 'add_mail_form.html', ctx)

wkshops_home/contact_book/templates/add_mail_form.html
{% extends "base.html" %}


{% block content %}

    <form action="#" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add New Mail">
    </form>

{% endblock %}

wkshops_home/contact_book/templates/add_phone_form.html
{% extends "base.html" %}


{% block content %}

    <form action="#" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add New Phone Number">
    </form>

{% endblock %}

wkshops_home/contact_book/templates/all_contacts.html
{% extends "base.html" %}

{% block content %}

<div class="contacts-list">
    <h2>All contacts available</h2>
    <ul>
        {% for contact in contacts %}
        <li>{{contact.name}}
            <button class="manage-contact">
                <a href="{% url 'contact-details' contact.id %}">
                    Details
                </a>
            </button>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

wkshops_home/contact_book/templates/all_groups.html
{% extends 'base.html' %}

{% block content %}

<div class="contacts-list">
    <h2>All groups available</h2>
    <ul>
        {% for group in contacts %}
        <li>{{group.name}}
            <button class="manage-contact">
                <a href="#">
                    Details
                </a>
            </button>
        </li>
        {% endfor %}
    </ul>
</div>


{% endblock %}

wkshops_home/contact_book/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Book</title>


    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'styles_cb.css' %}">

</head>
<body>
{% block header %}
<header>
    <div class="container">

        <img src="{% static 'logo.png' %}" alt="logo" class="logo">
        <nav>
            <ul>
                <li><a href="{% url 'index' %}"> Home </a> </li>
                <li><a href="{% url 'all-groups' %}"> Groups </a> </li>
                <li><a href="#"> Users </a> </li>
            </ul>
        </nav>

    </div>
</header>
{% endblock %}


<data>

    {% block content %}

    {% endblock %}

</data>


<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="{% static '/js/app.js' %}"></script>
</body>
</html>

wkshops_home/contact_book/templates/contact_book/person_form.html
{% extends "base.html" %}


{% block content %}

    <form action="#" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add New Contact">
    </form>

{% endblock %}

wkshops_home/contact_book/templates/contact_details.html
{% extends 'base.html' %}

{% block content %}


<div class="contact-container">

    <h2>{{contact.name}}</h2>

    <p>
        <i>({{contact.description}})</i>
    </p>



    <div class="contact-section">
        <button class="manage-contact">
                <a href="{% url 'add-phone' contact.id %}">
                    add phone
                </a>
        </button>
        <button class="manage-contact">
                <a href="{% url 'add-mail' contact.id %}">
                    add email address
                </a>
        </button>
        <h3 class="contact-header">Phone:</h3>
        <ul class="contact-details hidden">
            {% for phone in contact_phones %}
            <li>{{phone.number}} || {{phone.get_type_display}}</li>
            {% empty %}
            <p>No phone number defined</p>
            {% endfor %}
        </ul>
        <h3 class="contact-header">Mail:</h3>
        <ul class="contact-details hidden">
            {% for mail in contact_mails %}
            <li>{{mail.mail_address}} || {{mail.get_type_display }}</li>
            {% empty %}
            <p>No email defined</p>
            {% endfor %}
        </ul>
        <h3 class="contact-header">Address:</h3>
        <ul class="contact-details hidden">
            {% if contact_address %}
            <li>{{contact_address.city}}</li>
            {% else %}
            <button class="manage-contact">
                <a href="#">
                    add address
                </a>
            </button>
            {% endif %}
        </ul>

    </div>

</div>

{% endblock %}